version: '3.7'
services:

  postgresql:
    container_name: postgredb
    image: 'postgres:15'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=emotionDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - LANG=en_US.utf8
  pgadmin:
    container_name: pgadminemotion
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

